---

- hosts: proxmox
  name: Configure Proxmox
  gather_facts: true
  become: true
  roles:
    - role: proxmox_lxc
      when: proxmox_lxc_configure

- hosts: k3s_cluster
  name: Configure K3S cluster
  gather_facts: true
  roles:
    - role: lxc
      become: true
      when: proxmox_lxc_configure
    - role: prereq
      become: true
    - role: download
      become: true
    - role: raspberrypi
      become: true

- hosts: master
  name: Configure master nodes
  roles:
    - role: k3s/master
      become: true

- hosts: node
  name: Configure worker nodes
  roles:
    - role: k3s/node
      become: true

- hosts: master
  name: Post configure master nodes
  roles:
    - role: k3s/post
      become: true
