apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:pXGDBeeYxlpJwroObt9kSMWtgXanWOEWS+MUkWoM4CqBzJc=,iv:B6BigVf6wbo2vpFrXvM0qoc0tragkSFmNhYsf2UguKk=,tag:Qs/PXCKQCVpwafnzi1m97w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:zAdxtexUIql/+kOoFCGp//IfnYjSE33U6O0Oz75GQ9izP8NELQ==,iv:vBQ7TZ56J9yafCSl2y3urAP9tcmFC7gAdRt1yYQyBEQ=,tag:SEeCR2UiIDSsmXftgPuRDw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:ZCo8kQ48WX/W4N1gIUvrXTDUwRJoyN0=,iv:k6ImGw23uQ20bluwgfNMmz4V3lN6TCVBsQgmHtBmX/c=,tag:SWGQ1tpbo0XeJwQ3bo2Zfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQVZyTHpKRWE0d3RDcm5L
            dmhHZEdYTXJVWmUrN2YvOEZManNtU2lBcHk4ClBiUHZYcFNqSVFOa2xSSktUd2t0
            b2VhajJJbHFhOWZTS0ROSElLdFFVTFUKLS0tIHBOTGhRS2RnWndlNGRQWUNXOVRj
            M0xQcG01T2l3b3VISkdLeHkyaGhtV2MK5s0+HRVfSqZc8j7lgbgWs/g3xP6ocSzs
            qqiAy0a/t1S+sAQA4w9ByNDccXTZQ3mfm8xvcsxC9H11y+HuE9bZ/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T07:23:09Z"
    mac: ENC[AES256_GCM,data:4chXpjHXFW3l8eu0bX8hipXT/s6rqaCg5BW7car9R7SdzWPxJmo6h72MysrSWiA+tkpXtYu6F22+oz3CWQHZ1Gno/yIIMIxPaT+JxoC9SXlezoq7F9LdnzDG7nUOVnOrsnr2ter+6o8Tranatl4+zAD7x4QYTFXxJKhel2e3O1w=,iv:fX7HidxzwxLsJF9q562JNjr0ElGvU6+sjB9lmIeWNyU=,tag:W6zDWRRXd5pMI9xrDG9QBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
