kind: ENC[AES256_GCM,data:63ubZfP6,iv:mt03+Wz4aPLkQ49ejy93fjoRWKgG1qSAEkbBTQstJTQ=,tag:STxZaddtRoW8gx04i+KNcQ==,type:str]
ansible_user: ENC[AES256_GCM,data:kzv+OCkR,iv:37iOsyhZohxKFh1stPbTUrew/qsAGSd58cqhQc/2dZk=,tag:Y9jZCOKQ2wLelFDrLv1a/w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:AgwZltaxKYaoqZgD9eo1l0/nm1RD8eP1O312sfMhonI25glG+AMF0fs=,iv:IaRlx2jePZcIZCXSvbB5kpEDgNTUDXCy6xKoU+0WD9g=,tag:V8KjgIl2CmyXKpXC1HrZSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dTlVa0hTSDlnOGxLbmNS
            K3RpYmdqS1RRWUxWelpETzQxc2FoUnFFNVVZClA0SUgxOGt2aU1CUjJqcENEZVdG
            N2FiU2pGb1RzVUZqb2dCL1VQaW5xS0kKLS0tIEJHUThNY2ZKbDdHWnFsV3hkUEl0
            c2hhNFJ5bGgwOXN6THdOTHNpZXpzQlUK0QGlTznK9+LLnVpJGU5Wbsh3xZWRAm/i
            R6DiNuQ7GlSJgT+yI2BDezlzA9sAaW0TbBeCG6a4uT6J5uu9R5/FSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T06:52:28Z"
    mac: ENC[AES256_GCM,data:fDUQTyO1DyPa0BBzYLUEg25x0eerZqzMUqryO5Bf1Zrq9Jyr51LadhzAmPujFlSIdNR4N51gsVeTahK0/X+tuzgjJYwqMru5IQnN50y0qKlPcWw8fR28+d0ZFXwmUwUiUDWPEJy0Adplo8bos7fbFXXGXRR9Tp+praDoDlqY1Ng=,iv:SCQzp+VuiGHgrUhySW8ujitEShCJfNZqn/Q8yBOwpZA=,tag:m8E2MBy4YLkq2DVIozZuug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
