kind: ENC[AES256_GCM,data:29NIwoQ7,iv:qmgnDRMqFXJMg49mVdzrzMhpsHRVIUPU5Yy3d1h/elU=,tag:2PgSEDo1EKJMP/eDPg5H+A==,type:str]
ansible_user: ENC[AES256_GCM,data:j4PmDc3O,iv:qljU5kKlzbAsJKbOmfQ2vIcHQHuYpvJMsL8/9Q93yBo=,tag:5vuh8Hza1lmxc5LfdKZk4A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:yfsPdSK6PMFk8fWZK4XFHFyc3F56xl9Ip04x1BK2bntNnfz2LjPx2ew=,iv:Y4l5SVmit/Of8xlF6FF8LKnOOlQ4jFsDLrEFjc+wvlo=,tag:42tDMATep+2qvged5urIBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWE5NQ2x6NE56NmtTcnhZ
            TUdxMUhNdXJ5MHlITmsyaDM0WDV5R255cm5ZClJBdVZ5UHo2ZlVudFQ2NzBURjdN
            bElQVXp6VTJZLzUrV0ZxRGt6dnl5UVkKLS0tIG91NUtJU0hEVC9rc1lvMmFUR1B6
            UjUwTzV2TktWTG41djl2OGlTWG9OZGcKTNZ3fwl7gdK1IKvQrvu9+ojCqHYHF4h7
            syodkyHOT6qq+uwkfKJTf2VN1rsZCc6D1O2BWq+lKoXXGzBKQRi/Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T04:55:53Z"
    mac: ENC[AES256_GCM,data:gh/iARwP3FtEVdMRp6XOQk5f7WocoGR2gsqEsPvnKYgXPDP4BCYTP1V/R+U3a9ak3pmwTTdgL0IBe2yXiFCuU/S54uCl6NQD+2cZxcV4rjG0NlLj/LK0jBBhI/xzKLccUQszif9BF2mL4Tj++r9o0UPwUqhiw4No5CI8AIjh49s=,iv:/xxYWR6eJORAiyRS0OXlkMDOU22zOe2UcFrzx1EAdHg=,tag:8wZrLUotpxEFtCPluI63yg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
