kind: ENC[AES256_GCM,data:qvIMGq3W,iv:Xg4uUC8MPSblF00GyoSAlDmlMmAkY3h4rxQnPoDr2w0=,tag:SNCgvjCDLLBs3mDhrKSFNA==,type:str]
ansible_user: ENC[AES256_GCM,data:3/jUS04+,iv:2myL+sm05yMPnMUyegXWpISiOaVoeSqxYhEqAmqVa3s=,tag:OMD50e4vpMc1uBpWqCAS5g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Oed11fhfMJnsJuLCSHZ8GIXFtGpEQGiyn+V51BDsdcmIZUxp+F/d43c=,iv:QEuCSy68Wj/T/EBd+cDqT+SdF8LgdKPqq225Ron29hE=,tag:UhJLxRJX2Pnj88U6gU6M/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHllQnBIYTdodW5XYWZz
            REVwNFVFdDU4V0VWTG44d0llaTFyVEFURkY0CnRSVVNBLzVmK2Z3bUdZbHI3RDVE
            UG9vQjRGUkFDZUp1WXFPMjA5czVBU28KLS0tIERPaE5DRlBFWkRoajhmQ3h6Q2Fw
            aDhaSW9BWXBTYkVPVlNsSTQ2SzZRMmsKrmbCpbEqWvzrXjpk6wl09aQKhJS4X6/X
            zGMn2lt045sZjTQShxPnpj5wKEoKQi6+zLk8GDcTel49eZqgHYJkbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T06:52:28Z"
    mac: ENC[AES256_GCM,data:LP/vR8dPAxVHe08uRLWmsjuMUVp5432Kh9DwknqG+QA54BtgBUi0zBs1LHPxkQkqXVTr1yjWloEWfHp+eCSp6cCnzb5cxQ38lCONxolZ37ShljTXJynueXKwU7DTwCtqCeSO3C3LTFrDcz1M1ILeCwVfw2h/aQEv73kHe5SoBWM=,iv:y9UoEO9iNx/mCe4h1lzI/wrmNVroCncvalQQlof9PWo=,tag:5gzPQCDBTqpkBGn3leESDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
