---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-samdarshi-cc
  namespace: default
spec:
  secretName: local-samdarshi-cc-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.samdarshi.cc"
  dnsNames:
  - "local.samdarshi.cc"
  - "*.local.samdarshi.cc"
