kind: ENC[AES256_GCM,data:04RiS6TW,iv:1M404VYyfM9SHPLSqF8hpbLZ83CXbQtyd2wCof4YOD0=,tag:8Yg37Pn4QY9cyJBC+jpJfg==,type:str]
ansible_user: ENC[AES256_GCM,data:vRtwNupV,iv:LZb4sdaQEkRHOhNj51WewBQb+KnQo7ktidWGtpQI8+Q=,tag:lYerP2M0AyKF/yE75dMx3w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:AjNG4ocO6S3twnH3nVaee66qaYuRYPaokonWmbUy5/Y0ZyN5jn6WgD0=,iv:aj2ghbd9Px37gt15uJs2Osu421Aw973qioXEfteJa8k=,tag:l+nq4rwvHNJC7f81c1aJww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYc3UxcmVBVGpqWU1ucldK
            SmQxTEsrTFlsRk0wZW84MGlpajNmZ2E4SDJ3CnpqZmt2NFA4UTFjUHlaQlgyZFM1
            MnE4a0dUTCtFa0k0eER4c3JGYkJLQ2cKLS0tIHBROHRFZ2VpSzVrRlVMckE3MVZY
            SHpFY1lRQ0ZyY2g2em1xRTVkL250U00K0HkYPRC/9b3wBeF4mJr/xKvw/3CToks6
            Xpt6cPFhGvat+eOxU/hoPrw5tHh5OujkB6gpGeTZvKT3ZhP9FxeWbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T07:23:09Z"
    mac: ENC[AES256_GCM,data:ZcKC0ijJAlfa5kfxy5k4MCq7O0+9LcYFp4sMEo+HmSLqcPmbt2Q4sDXvcueGdxR9/DcDaep3QMhyIXf4ZtBP/vO1zw4jEmbPqz/S8cSyn4Yz+GwZCBrL6W80P/dcjYI7s9cqPenZKw+oIFdHL1mXDb/i9dgf0RItA6+iCtGWebU=,iv:J8inrS204LBPPeatGpV7k5sMcX+jOy7fc+D8cAwb+rc=,tag:+ZzDm9+dcNjw57UHPeD16w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
