apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:5xFC9WOVDE+uRx/LYJzIIlhcNqvnSuWGsDHUXrRONukwxXqfzftPmaCxbdgv44oOGCNQQ/lrBqhS+1PB,iv:ZP+aD1jF+ZQEn1aSlhOdW5VoA/hO5lWozvsJjv1izIQ=,tag:sN59LYfseiORIzXNzH21Ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQk92K2pHbjBCZlNuZzB0
            a0JIdnlJbEZ1Q2JIVCtBZ2xkRnJpZW5BaEJnCmJ2ZWxwOUhNR2YvMkxoSnNlckJu
            SWs4djlCcFArUFhrcGJNdEhIZ0VITzAKLS0tIFhQT050T2g4blI1MXNYeFRRck9i
            dGxwNFdmMHBiTFJyYlh3bDFwZlhFTk0K8C89HDg6SVlx+HAEapA5n2LisrCuw9Sq
            fOFcDImLPT8l39tcUpbRGzCSksw/Lw525djaTlvUINnCgRXTDUpTCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T04:55:55Z"
    mac: ENC[AES256_GCM,data:410ErM11XzFvzZUtibODCgfhHLnYqgyPZcMam1WjkMwWW64SsN+n0BtaamFnRc8IVwt+P+j5COgV7K33iy5sawQzvBmJU4ecXwK/EwWqI8eJ/3fCyrBHvqUGYb2dUz88L7IBjiIDtdnlH8q2Azx2/MhStnb1AexctBt8bnsi9Xs=,iv:N5CJedMzeaUNFnvMMbfpo7aZIA8v/85IwtSOpSasAYU=,tag:pmUctg9Jq9BTeP/+nLw4cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
