---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "192.168.5.255"
  METALLB_LB_RANGE: "192.168.5.200-192.168.5.230"
  METALLB_K8S_GATEWAY_ADDR: "192.168.5.201"
  METALLB_INGRESS_ADDR: "192.168.5.200"
