---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "192.168.5.254"
  METALLB_LB_RANGE: "192.168.5.220-192.168.5.230"
  METALLB_TRAEFIK_ADDR: "192.168.5.220"
  METALLB_INGRESS_ADDR: "192.168.5.221"
