name: check 

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "backend/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: true
    timeout-minutes: 20

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend/

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust Nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/db/
            src-tauri/target/
          key: cargo-${{ hashFiles('**/src-tauri/Cargo.lock') }}
          restore-keys: |
            cargo-

      - name: Run Cargo check 
        run: cargo check

